<?php

// Definition of RadioBase module root directory
define("RB_ROOT", dirname(__FILE__));

/**
 * @defgroup Hooks implementations
 * @{
 */

/**
 * Implements hook_boot()
 */

function radiobase_boot()
{
    //define("RB_ROOT", dirname(__FILE__));
    
    // Init modules
    RB_Database::setConnection();
}

/**
 * Implements hook_block_info()
 * @todo Move it to include file
 * @todo Describe more blocks!
 */

function radiobase_block_info()
{
    $blocks['rb_num_entries'] = array(
        'info' => t('Num entries in Radiobase'),
        'cache' => DRUPAL_NO_CACHE
    );
    
    return $blocks;
}

/**
 * Implements hook_menu()
 * Requires include file
 */

function radiobase_menu()
{
    require_once (RB_ROOT . "/includes/menu.inc");
    return _radiobase_menu();
}

/**
 * Implements hook_block_view()
 */

function radiobase_block_view($delta)
{
    switch($delta)
    {
        case 'rb_num_entries':
            $block['subject'] = t('Number of entries');
            if(user_access('access content'))
            {
                $num_parts = RB_Database::numParts();
                
                if($num_parts == 0)
                    $content = t("There are no parts in database");
                else if($num_parts == 1)
                    $content = t("There is 1 part in database");
                else
                    $content = t("There are @num parts in database", array("@num" => $num_parts));
                
                $block['content'] = $content;
            }
            
            break;
    }
    
    return $block;
}

/**
 * Implements hook_permission()
 */

function radiobase_permission()
{
    return array(
        "rb add items" => array(
            "title" => t("Add items in database"),
            "description" => t("Allow user to add items in database")
        ),
        
        "rb edit items" => array(
            "title" => t("Edit items in database"),
            "description" => t("Allow user to edit items stored in database")
        ),
        
        "rb admin items" => array(
            "title" => t("Administrator rights"),
            "description" => t("Allow user to administer database (ex. undo changes from log)")
        ),
        
        "rb add shops" => array(
            "title" => t("Add shops"),
            "description" => t("Allow user to add new shops in database")
        ),
        
        "rb edit shops" => array(
            "title" => t("Edit shops"),
            "description" => t("Allow user to edit shops in database")
        ),
        
        "rb update prices" => array(
            "title" => t("Update prices"),
            "description" => t("Allow user to update prices")
        )
    );
}

/**
 * @}
 */
